FUNDAMENTAL_ANALYSIS_API_KEY1 = 'a812dc7d35321ed0502ea50d8dc71be9'
FUNDAMENTAL_ANALYSIS_API_KEY2 = '853385276752be06484994837763eea9'
FUNDAMENTAL_ANALYSIS_API_KEY3 = '6cd769e65a016c55ad1a6ae36c99b54f'
FUNDAMENTAL_ANALYSIS_API_KEY4 = '81e528acd9682797052554364ef445d9'
TWITTER_CONSUMER_KEY = 'NZgYCz42hOZbCWhYlyQ2jkZz3'
TWITTER_CONSUMER_SECRET = 'DAb2BFtKMn7j7CHGaf2VRQZdaI8SnzPgjFP6fLfTZMFkoVE9bw'
TWITTER_ACCESS_TOKEN = '1400566792406380544-Lcm9nAYADI12tQ3lAgrQIILv0hZTqO'
TWITTER_ACCESS_TOKEN_SECRET = 'VVSrDNjCxARVHVSV8fgcZsIEze9OeQyhCswzDHVfBf7oZ'
FINNHUB_API_KEY = 'c3fhafqad3if6rt4i3t0'